# -*- coding: utf-8 -*-
"""Day-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118lv2S_9zPRBd2yc96mZkr-PcOfe-NAp
"""

from google.colab import drive
drive.mount('/content/drive')

"""# ***`DATATYPES`***



"""

String='Janu'
Integer=20
Float=20.3
Boolean=True
Complex=2+3j
print(Complex)
print(String)
print(Integer)
print(Float)
print(Boolean)
print(type(String))
print(type(Integer))
print(type(Float))
print(type(Boolean))
print(type(Complex))

List=[19,'janu',15,20.3,'jashu','Reviii']
print(List)
print(type(List))

Tuple=(19,'janu',15,20.3,'jashu','Reviii')
print(Tuple)
print(type(Tuple))

Set={19,'janu',15,20.3,'jashu','Reviii'}
print(Set)
print(type(Set))

Dict={1:'janu',2:'jashu',3:'Reviii'}
print(Dict)
print(type(Dict))

import numpy as np
Array=np.array([1,2,3,4,5])
print(Array)
print(type(Array))

"""# ***`VARIABLE DECLARATION`***"""

ANS='CAPTITAL LETTER VARIABLE'
ans='Small letters variables'
janu1859='Variable with combination of letters and numbers'
_janu='Variable starting with underscore'
janu_20='Variable with underscore'
print('janu1859 -',janu1859)
print('janu_20 -',janu_20)
print('ANS -',ANS)
print('ans -',ans)
print('_janu -',_janu)
print('janu_20 -',janu_20)

"""# ***`LOOPS IN PYTHON`***"""

#for loop
n = 4
for i in range(0, n):
    print(i)

#while loop
cnt = 0
while (cnt < 3):
    cnt+= 1
    print("Hello Trainer")

"""# ***`CONDITIONAL STATEMENT`***"""

n=int(input('Enter the number:'))
if n>0:
  print('Postive number')
elif n<0:
  print('Negative number')
else:
  print('The number is Zero')

n=int(input('Enter the number:'))
if n%2==0:
  print('Even number')
else:
  print('Odd number')

age = int(input("Enter your age: "))
citizen = input("Are you an Indian citizen? (yes/no): ").lower()

if age >= 18:
    if citizen == "yes":
        print("You are eligible Vote.")
    else:
        print("You are not eligible Vote.")
else:
    print("You are not eligible Vote.")

age=int(input('Enter your age:'))
youare='Adult' if age>=18 else 'Minor'
print(youare)

"""# ***`FUNCTIONS`***"""

def add(a,b):
  return a+b
addition=add(5,4)
print(addition)

def myFun(x, y=50):
    print("x: ", x)
    print("y: ", y)
myFun(10)

def cube(x):
  return x*x*x
print(cube(7))

square = lambda x : x*x
print(square(2))

def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(68))

